id: P97A678D4
initial_creation_type: input
source_metadata:
  title: Stages of Meditation Series
  language: en
  description: 'Texts that provide practical, step-by-step instructions on how to
    meditate on certain topics:'
  volume:
    60138ac5886a4f92a504323a1b5bc3c7:
      title: 'The Brightly Shining Sun: A Step-by-Step Guide to Meditating on the
        Bodhicaryāvatāra'
      parent: Bodhicaryāvatāra
    efa10bb08c964217afcd289730efb6a1:
      title: 'The Garland of Jewel Ornaments: The Stages of Meditating on the Bodhicaryāvatāra'
      parent: Bodhicaryāvatāra
    4f109d7acdf54d079face58247f7bc3d:
      title: 'A Casket of Sacred Dharma: Stages of Meditation on Dependent Arising'
      parent: Dependent Origination
    d8a4cddb77284f1ab8235b5d17b8e711:
      title: A Step-by-Step Meditation on the Definitive Meaning of the Great Middle
        Way
      parent: Middle Way
    6fb4ce3077684a88b246fa32646d0f1a:
      title: 'Excellent Explanation from the Scriptural Tradition: A Brief Guide to
        the Stages of Meditating on the General Themes of the Ornament to the Prajñāpāramitā'
      parent: Prajñāpāramitā
created_at: '2022-03-01T05:57:16.024340'
last_modified_at: '2022-03-01T05:57:16.024346'
